### ISSUE TITLE
from Classification to Regression using TL.

### ISSUE THREAD

**Issue by bemoregt** [chsasank/pytorch-tutorials#1]
Hi, @chsasank 

I'm a hot fan of your "Transfer learning code".

I have an idea with transfer learning with pytorch.

It is that converting image classification model to image regression model using transfer learning.

The procedure is here:
1. Train the CNN network with image classification datasets.
2. Removing the last Classification header(FC layers).
3. Adding the new Regression FC header.
4. Retrain the CNN network using Transfer learning with image regression datasets.

Image Regression network means image-input and  scalar-value-output network for physical value regression(temperature, length, energy, count of object, etc).

But, Becaus of my short pytorch skills, I cannot change your classification train source to regression training source.

How can I change your source to regression train source with transfer learning?

Thanks in advance.

Best,

from @bemoregt.

**Comment by chsasank** [comment]
Hey sorry for late reply. I was not checking my github issues. Why don't you post at https://discuss.pytorch.org/?

Somebody would be happy to help you there.
